Refactored Email Notification configuration and scheduler
codice/ddf-ui pull request #26
Opened 2016-10-17 15:48 UTC by bdeining

#### What does this PR do?
This PR fixes email notification scheduling and configuration update
#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged; if a component team is listed, at least one of its members needs to approve)?
@lcrosenbu @glenhein 
#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).
@andrewkfiedler
@jlcsmith 
#### How should this be tested?
Build and Install DDF, configure admin to use a valid email, configure email notification and query monitor, create a workspace with standing queries and subscribe to it, and observe emails are being sent out at the proper interval.
#### Any background context you want to provide?
#### What are the relevant tickets?
#### Screenshots (if appropriate)
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

2016-10-17 16:39 UTC, glenhein requested changes

2016-10-17 16:39 UTC, glenhein commented on catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/monitor/email/EmailNotifier.java
> +        properties.setProperty("mail.smtp.auth", "false");
nit: since the other property strings are defined as constants, it would be consistent to have "mail.smtp.auth" defined as a constant.

2016-10-17 16:39 UTC, glenhein commented on catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/blueprint/blueprint.xml
> +        <argument value="example.mail.protection.outlook.com"/>
Is there a reasonable default value for the mail host? I'm thinking it should be an empty string.

2016-10-17 16:39 UTC, glenhein commented on catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.email.xml
> +            default="example.mail.protection.outlook.com"/>
Is there a reasonable default value for the mail host? I'm thinking it should be an empty string.

2016-10-17 19:29 UTC, rzwiefel commented on catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.email.xml
> +            default="example.mail.protection.outlook.com"/>
I would say `localhost`, if nothing else.

2016-10-17 20:04 UTC, bdeining commented on catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/monitor/email/EmailNotifier.java
> +        properties.setProperty("mail.smtp.auth", "false");
Done

2016-10-17 20:04 UTC, bdeining commented on catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/blueprint/blueprint.xml
> +        <argument value="example.mail.protection.outlook.com"/>
Went with localhost

2016-10-17 20:04 UTC, bdeining commented on catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.email.xml
> +            default="example.mail.protection.outlook.com"/>
Went with localhost

2016-10-17 22:56 UTC, rzwiefel commented on catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/monitor/api/WorkspaceQueryService.java
> +     * Run all scheduled queries known to the WorkSpaceQueryService
Why not just do `public interface WorkspaceQueryService extends Runnable` ?

2016-10-18 19:15 UTC, lcrosenbu approved these changes

2016-10-18 19:15 UTC, lcrosenbu commented on catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.email.xml
> +            default="The workspace '%[attribute=id]' contains up to %[hitCount] query hits."/>
Recommend replacing `query hits` with `search results`.

2016-10-19 13:53 UTC, bdeining commented on catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/monitor/api/WorkspaceQueryService.java
> +     * Run all scheduled queries known to the WorkSpaceQueryService
I'm hesitant to extend Runnable in this interface.  The run method itself isn't intended to be executed in a separate thread.

2016-10-20 15:34 UTC, bdeining commented on catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.email.xml
> +            default="The workspace '%[attribute=id]' contains up to %[hitCount] query hits."/>
changed

2016-10-27 19:26 UTC, jlcsmith requested changes

2016-10-27 19:26 UTC, jlcsmith commented on catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/monitor/impl/WorkspaceQueryServiceImpl.java
> +
nit: any reason not to use "notNull" here to be consistent with the above?

2016-10-27 19:26 UTC, jlcsmith commented on catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/monitor/impl/WorkspaceQueryServiceImpl.java
> +            LOGGER.debug("Scheduling job {}", jobDetail);
it looks like it is possible that the jobDetail is null.

2016-10-28 19:45 UTC, jlcsmith requested changes

2016-10-28 19:45 UTC, jlcsmith commented on catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.email.xml
> +            default="[%[attribute=id]] workspace query notice"/>
Please change to

> Workspace '%[attribute=title]' notification

2016-10-28 19:45 UTC, jlcsmith commented on catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.email.xml
> +            default="The workspace '%[attribute=id]' contains up to %[hitCount] results."/>
Please change to

> The workspace '%[attribute=title]' contains up to %[hitCount] results.  Log in to see results https://localhost:8993/search/catalog/#workspaces/%[attribute=id]

2016-10-28 20:07 UTC, bdeining commented on catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/monitor/impl/WorkspaceQueryServiceImpl.java
> +            LOGGER.debug("Scheduling job {}", jobDetail);
added `notNull` for jobDetail

2016-10-28 20:07 UTC, bdeining commented on catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/monitor/impl/WorkspaceQueryServiceImpl.java
> +
changed to `notNull`

2016-10-28 20:08 UTC, bdeining commented on catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.email.xml
> +            default="[%[attribute=id]] workspace query notice"/>
done

2016-10-28 20:08 UTC, bdeining commented on catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.email.xml
> +            default="The workspace '%[attribute=id]' contains up to %[hitCount] results."/>
done

2016-10-31 20:36 UTC, jlcsmith approved these changes

2016-10-31 20:37 UTC, merged