[3.6.x] DDF-351 Extension Point for Security Logging
codice/ddf-ui pull request #352
Opened 2020-09-01 23:42 UTC by cantstoptheunk

- Adds a security logging function that can be used downstream.
- If a downstream application does not fill out a function definition then the code will no-op and do nothing.

2020-09-01 23:43 UTC, andrewkfiedler requested changes
If this is centered around the inspector visual, shouldn't we be tying it into that visual rather than the result selector?

2020-09-02 20:28 UTC, cantstoptheunk commented on ui-frontend/packages/catalog-ui-search/src/main/webapp/component/result-selector/result-selector.tsx
> -import Extensions from '../../extension-points'
should probably not delete

2020-09-02 20:30 UTC, cantstoptheunk commented on ui-frontend/packages/catalog-ui-search/src/main/webapp/component/visualization/inspector/inspector-lazy.tsx
> +    for (let key in selectedResults) {
call it id instead of key

2020-09-02 20:32 UTC, cantstoptheunk commented on ui-frontend/packages/catalog-ui-search/src/main/webapp/component/visualization/inspector/inspector-lazy.tsx
> +    for (let key in selectedResults) {
object.keys() to grab the list of keys

2020-09-03 17:11 UTC, bellcc requested changes
This extension point is too specific. It will only have one purpose. I think we should put the audit logging code entirely in DDF-UI.

2020-09-16 20:37 UTC, andrewkfiedler commented
Going to go a different route on this

2020-09-16 20:37 UTC, closed without merging