Removed function that was causing unexpected browser close
codice/ddf-ui pull request #657
Opened 2022-07-12 07:05 UTC by wesleyclee

###
What does this PR do, and why?
- Bugfix change for when opening DDF in a new tab, performing a metacard interaction on returned search result would close the current window.
- Removed unnecessary code that was introducing the bug
###
How should this be tested?
1. Create a simple HTML page to open DDF in a new tab
```
<html>
<body>
<a href="https://isr-cn2a-sys-01.aur.nciteglobal.com.au:8993/" target="_blank">Launch ISRI</a>
</body>
</html>
```
 2.  Open the page with Chrome or Firefox, and click on the link.  This will open DDF.
 3.  Navigate to the search tab, and conduct a search that returns at least 1 result.
 4.  Select the result
 5.  Using the kebab menu at the top of the window (next to the heart), perform an action.
 6. The tab no longer closes.

2022-07-14 23:31 UTC, andrewkfiedler approved these changes

2022-07-18 16:30 UTC, andrewkfiedler approved these changes

2022-07-18 16:30 UTC, andrewkfiedler commented on ui-frontend/packages/catalog-ui-search/src/main/webapp/component/result-selector/result-selector.tsx
> -            onClose={() => {
On close is required as a parameter, so pass in an empty function for now.

2022-07-28 23:17 UTC, wesleyclee commented on ui-frontend/packages/catalog-ui-search/src/main/webapp/component/result-selector/result-selector.tsx
> -            onClose={() => {
@andrewkfiedler The change above has been made, can this PR be merged soon?

2022-08-01 02:52 UTC, nnld reviewed
Hero is in progress.

2022-08-01 04:27 UTC, nnld approved these changes
Hero succeeded.  All good.

2022-08-03 03:06 UTC, nnld approved these changes

2022-08-05 00:47 UTC, nnld requested changes
We have found another instance where this issue is manifested.  Potentially, there will be more instances where this method is called.  We will need to fix them all in this PR.

2022-08-25 22:14 UTC, andrewkfiedler commented
> We have found another instance where this issue is manifested. Potentially, there will be more instances where this method is called. We will need to fix them all in this PR.

@nnld is there going to be further updates to this PR?

2022-08-25 22:15 UTC, jlcsmith approved these changes

2022-08-26 01:06 UTC, wesleyclee commented
@andrewkfiedler We are still investigating and testing to find more occurrences of this bug within DDF-UI, and will make the fixes where we think is appropriate and update this PR. After that we will ping you guys for another review

2022-09-11 23:03 UTC, wesleyclee commented
@andrewkfiedler We have finished looking into similar cases of the close() function being called unintentionally, and have tested and confirmed that no similar cases exist. This PR is ready to be merged

2022-09-12 14:59 UTC, merged