Add Color Selector to Searches
codice/ddf-ui pull request #782
Opened 2023-06-30 18:39 UTC by pvargas

This PR adds the ability to change the color of drawn shapes in searches.

![Screenshot 2023-06-30 at 14 33 50](https://github.com/codice/ddf-ui/assets/12192559/74b0013e-13be-4d1e-a113-fec45617d6f8)

2023-06-30 19:06 UTC, pvargas commented
build now

2023-07-03 21:12 UTC, jrnorth commented on ui-frontend/packages/catalog-ui-search/src/main/webapp/react-component/location/location-color-selector.tsx
> +  border-radius: 4px;
Do we need to set these, since they're set to the same values in `ColorSwatch`?

2023-07-03 21:12 UTC, jrnorth commented on ui-frontend/packages/catalog-ui-search/src/main/webapp/react-component/location/location-color-selector.tsx
> +const ColorPaletItem = ({ title, colorValue, setColor }: ColorSwatchProps) => {
`ColorPaletteItem`

2023-07-03 21:12 UTC, jrnorth commented on ui-frontend/packages/catalog-ui-search/src/main/webapp/react-component/location/location.tsx
> +                  onBlur={() => {
Should this be `onClose`?

2023-07-03 21:12 UTC, jrnorth commented on ui-frontend/packages/catalog-ui-search/src/main/webapp/react-component/location/location.tsx
> +  const handleOpenColorSelector = () => {
We should be explicit about the state we want to set. Clicking the color square should set `openColors` to true, not just flip its current value. Likewise, the close handler should set it to false.

2023-07-05 14:24 UTC, pvargas commented on ui-frontend/packages/catalog-ui-search/src/main/webapp/react-component/location/location.tsx
> +                  onBlur={() => {
I don't think so. The intent is to set `openColors` to `false` after the component loses focus (a color is selected or the user clicks away).

2023-07-05 18:07 UTC, jrnorth approved these changes

2023-07-05 18:28 UTC, andrewkfiedler requested changes

2023-07-05 18:28 UTC, andrewkfiedler commented on ui-frontend/packages/catalog-ui-search/src/main/webapp/react-component/location/location.tsx
> +  const [openColors, setOpenColors] = React.useState(false)
We have a reuseable hook to make these menus simpler to use.  

useMenuState is exported from menu-state.tsx.

It provides both the individual MuiPopoverProps and MuiButtonProps as things you can pass directly into those.

So like:
```
const {MuiButtonProps, MuiPopoverProps} = useMenuState()

<ColorSquare
                  disabled={isDrawing}
                  color={state.color}
                 
                  {...useTheme()}
                 {...MuiButtonProps}
                  size={'1.8rem'}
                />
           <Popover {...MuiPopoverProps} />
```

2023-07-05 19:51 UTC, pvargas commented on ui-frontend/packages/catalog-ui-search/src/main/webapp/react-component/location/location.tsx
> +  const [openColors, setOpenColors] = React.useState(false)
Nice. Made the change. Thanks!

2023-07-06 01:47 UTC, alexabird commented
❓ Now that we are able to specify colors, should we use the specified color rather than the arbitrary blue when in drawMode? Or use a color that is not an option in the color-selector?

https://github.com/codice/ddf-ui/assets/14789712/55997c60-8d2e-4777-9656-617d27c618b5

2023-07-06 01:48 UTC, alexabird approved these changes
❓ Now that we are able to specify colors, should we use the specified color rather than the arbitrary blue when in drawMode? Or use a color that is not an option in the color-selector?

https://github.com/codice/ddf-ui/assets/14789712/55997c60-8d2e-4777-9656-617d27c618b5

2023-07-06 17:04 UTC, andrewkfiedler approved these changes

2023-07-10 20:55 UTC, pvargas commented
> ❓ Now that we are able to specify colors, should we use the specified color rather than the arbitrary blue when in drawMode? Or use a color that is not an option in the color-selector?

Ended up going with the second option, but these changes now depend on an outstanding geospatialdraw PR.

2023-07-11 19:56 UTC, alexabird commented
build now

2023-07-11 20:56 UTC, merged